### ISSUE TITLE
Hmm

### ISSUE THREAD

**Issue by Sam152** [andrew-t/mines#2]
:)

<img width="528" alt="Screen Shot 2020-08-17 at 8 28 28 am" src="https://user-images.githubusercontent.com/820219/90347536-a56d2880-e063-11ea-952a-3643b7f9d2f8.png">

**Comment by Sam152** [comment]
So, I guess this works as designed, since while the move was a guess, there wasn't technically a safe move in the original square. My mistake.

Great concept and execution by the way.

**Comment by FranklinYu** [comment]
Actually there is a safe move. The one at bottom-left of 2 is never a mine.
